- name: Install Python and pip, and install requests
  become: yes
  tasks:
    - name: Install Python and pip
      apt:
        update_cache: yes
        name: python3-pip
        state: present

    - name: Gather facts
      setup:

    - name: Requests install
      pip:
        name: requests
        executable: python
