- name: Install Python and pip
  become: yes
  apt:
    update_cache: yes
    name: 
      - python3
      - python3-pip
    state: present

- name: Requests install
  pip:
    name: requests
    executable: "{{ ansible_python_interpreter }}"
